# k8s/go-service/service-go.yaml
apiVersion: v1
kind: Service
metadata:
  name: ml-service-go-service
  namespace: go-mlops
  labels:
    app: ml-service-go
spec:
  # The service must select the pods created by your Deployment
  selector:
    app: ml-service-go
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by the Service (used by Ingress)
      targetPort: 8080 # Port your Go application listens on
  type: ClusterIP
