apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garage

resources:
  - statefulset.yaml
  - service.yaml

configMapGenerator:
- name: garage-config
  files:
    - garage.toml

# Force the replacement of the name in the StatefulSet
replacements:
  - source:
      kind: ConfigMap
      name: garage-config
      fieldPath: metadata.name
    targets:
      - select:
          kind: StatefulSet
          name: garage
        fieldPaths:
          - spec.template.spec.volumes.[name=config].configMap.name
