apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: garage
spec:
  serviceName: "garage"
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
      - name: garage
        image: dxflrs/garage:v0.9.0
        env:
        - name: GARAGE_METADATA_DIR
          value: "/var/lib/garage/meta"
        - name: GARAGE_DATA_DIR
          value: "/var/lib/garage/data"
        - name: GARAGE_REPLICATION_MODE
          value: "none"
        - name: GARAGE_RPC_BIND_ADDR
          value: "[::]:3901"
        - name: GARAGE_RPC_SECRET
          value: "9d15abb685c2fe3c487af278be5f4789b2720c7268669bb589cb9650153f7519"
        - name: GARAGE_S3_REGION
          value: "garage"
        - name: GARAGE_S3_API_BIND_ADDR
          value: "[::]:3900"
        - name: GARAGE_S3_ROOT_DOMAIN
          value: ".s3.garage"
        - name: GARAGE_ADMIN_API_BIND_ADDR
          value: "[::]:3903"
        volumeMounts:
        - name: meta
          mountPath: /var/lib/garage/meta
        - name: data
          mountPath: /var/lib/garage/data
        - name: config-volume
          mountPath: /etc/garage.toml
          subPath: garage.toml
      volumes:
      - name: config-volume
        configMap:
          name: garage-config
  volumeClaimTemplates:
  - metadata:
      name: meta
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
