# k8s/mlsolid-service/connection.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlsolid-service
spec:
  selector:
    app: mlsolid-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: rest
      protocol: TCP
      port: 5000
      targetPort: 5000
