# k8s/mlsolid-service/connection.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlsolid-service
spec:
  # ClusterIP Service for internal communication (Traitraitefik)
  selector:
    app: mlsolid-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
