# k8s/mlsolid-service/connection.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlsolid-service
spec:
  selector:
    app: ml-service-python  # Matches the label in your deployment
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: rest
      protocol: TCP
      port: 80         # Port accessible for other pods in the cluster
      targetPort: 80   # Port where FastAPI listens inside the container
