# ArgoCD Application Definition for the MLflow Helm Chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-helm-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Set the repository source to the Git repository (where k8s/ is located)
    repoURL: https://github.com/pvavrina/goml.git
    # Chart name
    chart: mlflow
    # Target version of the community chart
    targetRevision: 1.8.1
    helm:
      # Explicitly define the external chart repository URL where the chart is located
      repository:
        url: https://community-charts.github.io/helm-charts
      # Reference the custom values file
      valueFiles:
        - k8s/helm/mlflow/values-mlflow.yaml
  destination:
    server: https://kubernetes.default.svc
    # Deploy to the go-mlops namespace
    namespace: go-mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
