# k8s/postgres/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres # Logical label for the Service object itself
spec:
  selector:
    # This must match the label on the actual PostgreSQL Pod/Deployment
    # which is currently set to app: strapi-db
    app: strapi-db 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
