# k8s/angular-frontend/service.yaml
# Angular Frontend Service

apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: go-mlops
  labels:
    app: angular-frontend
spec:
  type: ClusterIP
  selector:
    app: angular-frontend
  ports:
  - port: 80 
    targetPort: 80 # Targets the Nginx container port
    protocol: TCP
